# Generated by Django 4.2.2 on 2023-06-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название мероприятия')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание мероприятия')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, verbose_name='Название доклада')),
                ('date', models.DateField(verbose_name='Дата доклада')),
                ('start_time', models.TimeField(verbose_name='Начало доклада')),
                ('end_time', models.TimeField(verbose_name='Окончание доклада')),
                ('isfinished', models.BooleanField(default=False, verbose_name='Доклад завершен?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='telegrambot.event', verbose_name='Мероприятие')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=500, unique=True, verbose_name='Никнейм клиента')),
                ('isspeaker', models.BooleanField(default=False, verbose_name='Является спикером?')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answered', models.BooleanField(default=False, verbose_name='Отвечен?')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='telegrambot.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='telegrambot.user')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='telegrambot.user', verbose_name='Спикер'),
        ),
    ]
