# Generated by Django 4.2.2 on 2023-06-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SomeUser',
        ),
    ]
