# Generated by Django 4.2.2 on 2023-06-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_rename_user_someuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SomeUser',
            new_name='Listener',
        ),
    ]
