# Generated by Django 4.2.2 on 2023-06-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_rename_someuser_listener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='listener',
        ),
    ]
