# Generated by Django 4.2.2 on 2023-06-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_listener_is_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='chat_id',
            field=models.CharField(default=12345678, max_length=50, verbose_name='Chat ID'),
            preserve_default=False,
        ),
    ]
